import React from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../../../../styles/EditProfileWorker.module.css";
import gStyle from "../../../../styles/General.module.css";

export default function index() {
  return (
    <>
      <Head>
        <title>Edit profile worker - HireJob</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <div className={`position-relative ${styles["kontent-wrapper"]}`}>
        <div className={`${styles["bg-purple"]}`}></div>
        <div className={`${styles["card-aside-left"]} d-flex bg-primary`}>
          <div className="info-wrapper w-100 d-flex flex-column justify-content-center align-items-center">
            <div className={`img-wraper  w-100 bg-white d-flex justify-content-center align-items-center`}>
              <img src="/assets-img/Louis Tomlinson.png" alt="" className="pt-5 pb-2"/>
            </div>
            <form className="img-edit w-100">
              <div className="bg-white ">
                <div className="sect-form-wrapper d-flex gap-2 justify-content-center align-items-center w-100">
                  <div className="edit-icon ">
                    <input
                      type="file"
                      id="photo-worker"
                      style={{ display: "none" }}
                    />
                    <i class="bi bi-pencil-fill text-muted"></i>
                  </div>
                  <div>
                    <label
                      htmlFor="photo-worker"
                      className={`${gStyle["open_sans_lt"]}`}
                    >
                      Edit
                    </label>
                  </div>
                </div>
                <div className="ms-3 name-person mb-2 mt-2">
                  <p className={` ${gStyle['open_sans_sb']} h4`}> Louis Tomlinson </p>
                </div>
                <div className="ms-3 job-person">
                  <p className={` ${gStyle['open_sans_sb']} text-muted`}> Web Developer </p>
                </div>
                <div className="ms-3 location-person d-flex">
                  <div className="icon-map">
                    <i className="bi bi-geo-alt"></i>
                  </div>
                  <div className="detail-location">
                    <p>Purwokerto, Jawa Tengah</p>
                  </div>
                </div>
                <div className="ms-3 job-prefer">
                  <p>Freelancer</p>
                </div>
              </div>

            </form>
          </div>
        </div>
      </div>
    </>
  );
}

index.layout = "L2";
