import React, { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../../../styles/Portofolio.module.css";
import gStyle from "../../../styles/General.module.css";
import { WorkExp, Portofolio } from "../../../components/ProfileSect.jsx";
import { useRouter } from "next/router";
import axios from "axios";


export default function index() {
    // const token = localStorage.getItem('token');
    // console.log(token)
    const [showPortofolio, setShowPortofolio] = useState(true);

    const [showWorkExp, setShowWorkExp] = useState(false);

    const [data, setData] = useState([]);

    const router = useRouter()
    const { id } = router.query;
    console.log(id);
    // const [userId, setUserId] = useState(id);




    useEffect(() => {
        axios
            .get(`http://localhost:5000/v1/user/ava_users/${id}`)
            .then((res) => {
                console.log(res)
                setData(res.data.data.rows)
            })
            .catch((err) => {
                console.log(err)
            })
    }, [id])

    console.log(data)

    const onPortofolio = () => {
        setShowPortofolio(true);
        setShowWorkExp(false);
    };

    const onWorkExp = () => {
        setShowPortofolio(false);
        setShowWorkExp(true);
    };
    return (
        <>
            <Head>
                <title>Profile portofolio - HireJob</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/icon.png" />
            </Head>

            <div className={`position-relative ${styles["kontent-wrapper"]}`}>
                <div className={`${styles["bg-purple"]}`}></div>
                {data.map((item, index) => (
                    <div className={`position-absolute ${styles["card-aside"]}`}>
                        <div
                            className={` ${styles["img-wrapper"]} d-flex flex-column justify-content-center align-items-center  col-12`}
                        >
                            <div className={` ${styles["img-card"]}`}>
                                <img
                                    src={`http://localhost:5000/ava_user/${item.avatar}`}
                                    className={`${styles["img-content"]}`}
                                    alt="Louis Tomlinson"
                                />
                            </div>
                        </div>
                        <div className={`${styles["info-wrapper"]} d-flex flex-column`}>
                            <div className="ms-3 mb-1 name-info ">
                                <p className={`${gStyle["open_sans_sb"]} h4`}>{item.full_name}</p>
                            </div>
                            <div className="ms-3 name-info">
                                <p className={`${gStyle["open_sans_lt"]}`}>{item.job_desc ? (<p>{item.job_desc}</p>) : (<p>Job Type: ---</p>)}</p>
                            </div>
                            <div className="ms-3 location-info d-flex gap-2">
                                <div className="map-icon">
                                    <i className="text-muted  bi bi-geo-alt"></i>
                                </div>
                                <div className="desc-location">
                                    <p className={`text-muted  ${gStyle["open_sans_lt"]}`}>
                                        {item.domisli ? (<p>{item.domisli}</p>) : (<p>unknown</p>)}
                                    </p>
                                </div>
                            </div>
                            <div className={`ms-3 job-spec`}>
                                <p className={`text-muted  ${gStyle["open_sans_lt"]}`}>
                                    {item.job_spec ? (<p>{item.domisli}</p>) : (<p>Job spec: ---</p>)}
                                </p>
                            </div>
                            <div className="ms-3 desc-person w-75">
                                <p className={`text-muted  ${gStyle["open_sans_lt"]}`}>
                                    {item.personal_desc ? (<p>{item.personal_desc}</p>) : (<p>Personal desc: ---</p>)}
                                </p>
                            </div>
                            <div className="ms-3 mb-5 hire-btn d-flex w-75">
                                <button
                                    type="button"
                                    className={`btn ${styles["btn-purple"]} w-100`}
                                >
                                    <p className={`${gStyle["open_sans_sb"]}`}>Hire</p>
                                </button>
                            </div>
                            <div className="ms-3 mb-5 hire-btn d-flex w-75">
                                <Link href="/profile/edit_profile/worker" className="w-100">
                                    <button
                                        type="button"
                                        className={`btn ${styles["btn-purple"]} w-100`}
                                    >
                                        <p className={`${gStyle["open_sans_sb"]}`}>Edit Profile</p>
                                    </button>
                                </Link>
                            </div>
                            <div className={`ms-3 mb-5 skills-wrapper d-flex flex-column`}>
                                <div className="title">
                                    <p className={`${gStyle["open_sans_sb"]} h4`}>Skill</p>
                                </div>
                                <div className={`${styles["wrap-skill"]} row gap-2`}>
                                    <div className="skill-name col-5">
                                        <button
                                            type=""
                                            className={`btn ${styles["btn-skill-custom"]} `}
                                        >
                                            <p className={`${styles["open_sans_sb h6"]}`}>Python</p>
                                        </button>
                                    </div>
                                    <div className="skill-name col-5">
                                        <button
                                            type=""
                                            className={`btn ${styles["btn-skill-custom"]} `}
                                        >
                                            <p className={`${styles["open_sans_sb h6"]}`}>Python</p>
                                        </button>
                                    </div>
                                    <div className="skill-name col-5">
                                        <button
                                            type=""
                                            className={`btn ${styles["btn-skill-custom"]} `}
                                        >
                                            <p className={`${styles["open_sans_sb h6"]}`}>Python</p>
                                        </button>
                                    </div>
                                    <div className="skill-name col-5">
                                        <button
                                            type=""
                                            className={`btn ${styles["btn-skill-custom"]} `}
                                        >
                                            <p className={`${styles["open_sans_sb h6"]}`}>Python</p>
                                        </button>
                                    </div>
                                    <div className="skill-name col-5">
                                        <button
                                            type=""
                                            className={`btn ${styles["btn-skill-custom"]} `}
                                        >
                                            <p className={`${styles["open_sans_sb h6"]}`}>Python</p>
                                        </button>
                                    </div>
                                </div>
                            </div>
                            <div className="ms-3 mb-5 socmed-wrapper d-flex flex-column">
                                <div className="mail-address-content d-flex gap-2">
                                    <div className="mail-logo">
                                        <i className="bi bi-envelope"></i>
                                    </div>
                                    <div className="mail-address">
                                        <p className={`${styles["open_sans_lt"]} text-muted`}>
                                            Louistommo@gmail.com
                                        </p>
                                    </div>
                                </div>
                                <div className="ig-content d-flex gap-2">
                                    <div className="ig-logo">
                                        <i className="bi bi-instagram"></i>
                                    </div>
                                    <div className="ig-name">
                                        <p className={`${styles["open_sans_lt"]} text-muted`}>
                                            @Louist91
                                        </p>
                                    </div>
                                </div>
                                <div className="github-content d-flex gap-2">
                                    <div className="github-logo">
                                        <i className="bi bi-github"></i>
                                    </div>
                                    <div className="github-name">
                                        <p className={`${styles["open_sans_lt"]} text-muted`}>
                                            @Louisttommo
                                        </p>
                                    </div>
                                </div>
                                <div className="tiktok-content d-flex gap-2">
                                    <div className="tiktok-logo">
                                        <i className="bi bi-tiktok"></i>
                                    </div>
                                    <div className="mail-address">
                                        <p className={`${styles["open_sans_lt"]} text-muted`}>
                                            @Louistommo91
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                ))
                }
                <div className={`position-absolute ${styles["card-aside-right"]}`}>
                    <div className="ms-3 link-wrapper d-flex gap-5">
                        <div className="mt-3 portofolio-Link">
                            <button
                                className="btn"
                                type="button"
                                onClick={onPortofolio}
                                style={
                                    showPortofolio
                                        ? { borderBottom: "3px solid #5E50A1", background: "none" }
                                        : {}
                                }
                            >
                                <p className={`${styles["open_sans_sb"]} h4 text-black`}>
                                    Portofolio
                                </p>
                            </button>
                        </div>
                        <div className="mt-3 portofolio-Link">
                            <button
                                className="btn"
                                type="button"
                                onClick={onWorkExp}
                                style={
                                    showWorkExp
                                        ? { borderBottom: "3px solid #5E50A1", background: "none" }
                                        : {}
                                }
                            >
                                <p className={`${styles["open_sans_sb"]} h4 text-black`}>
                                    Pengalaman kerja
                                </p>
                            </button>
                        </div>
                    </div>
                    <div className="ms-3 mt-3 work-exp-wrapper">
                        {showWorkExp ? <WorkExp /> : null}
                    </div>
                    <div className="ms-3 mt-3 kontent-wrapper">
                        {showPortofolio ? <Portofolio /> : null}
                    </div>
                </div>
            </div>


        </>
    );
}

index.layout = "L2";
