import React from 'react'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import gStyle from '../../styles/General.module.css'

export default function index() {
  return (
    <>
      <Head>
        <title>Home - HireJob</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <div className='w-100 mb-5'>
        <div className={` ${styles['wrapper-top']} d-flex`}>
          <div className='m-5 title d-flex justify-content-center align-items-center'>
            <p className={`h3 text-white ${styles['open_sans_sb']}`} >Top Jobs</p>
          </div>
        </div>
        <div className='wrapper-search mb-5'>
          <div className={`m-5 ${styles['form-input']} d-flex align-items-center`}>
            <form className='ms-5 w-100 d-flex'>
              <div className='col-9'>
                <input type="text" className={`${styles['search-input']} `} name="search" placeholder='search for any skill' />
              </div>
              <div className='col-2 d-flex align-items-center'>
                <div className={`ms-2 ${styles['icon-search']}`}>
                  <i className="bi bi-search ps-5"></i>
                </div>
                <div className='ms-3 select-category'>
                  <select className={`form-select ${styles['custom-form-select']}`} aria-label="Default select example">
                    <option selected>Kategori</option>
                    <option value="1">One</option>
                    <option value="2">Two</option>
                    <option value="3">Three</option>
                  </select>
                </div>
              </div>
              <div className='col-1 d-flex align-items-center justify-content-center'>
                <div className='button-submit'>
                  <button type="button" className={`btn ${styles['btn-purple']} ${gStyle['open_sans_sb']}`}>Search</button>
                </div>
              </div>

            </form>
          </div>
        </div>
        <div className='mb-5'>

        </div>
        <div className='wrapper-person'>
          <div className={`m-5 ${styles['person-card']} bg-success d-flex`}>
            <div className={` col-3 bg-warning d-flex justify-content-center align-items-center`} >
              <img src="/assets-img/banner-auth.jpg" alt="louis tomlinson" className={`${styles['image-content']}`} />
            </div>
            <div className='person-info-wrapper d-flex flex-column align-items-center justify-content-center'>
              <div className='person-name'>
                <p>Louis Tomlinson</p>
              </div>
              <div className='person-job'>
                <p>Web developer</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}

index.layout = 'L2';
